version: '3'
services:
  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=auth_db
    ports:
      - 5432:5432
  product-db:
    image: postgres
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=product-db
    ports:
      - 5433:5432
  sales-db:
    image: mongo
    container_name: sales-db
    restart: always
    environment:
      - MONGODB_USER=docker
      - MONGODB_PASSWORD=docker
      - MONGODB_DATABASE=sales-db
    ports:
      - 27017:27017
      - 28017:28017
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
