version: '3'
services:
  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=auth_db
    ports:
      - 5432:5432
  product-db:
    image: postgres
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=product-db
    ports:
      - 5433:5432
  sales-db:
    image: mongo
    container_name: sales-db
    restart: always
    environment:
      - MONGODB_USER=docker
      - MONGODB_PASSWORD=docker
      - MONGODB_DATABASE=sales-db
    ports:
      - 27017:27017
      - 28017:28017
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
  auth-api:
    container_name: auth-api
    build: './auth-api'
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - auth-db
  product-api:
    container_name: product-api
    build: './products-api'
    environment:
      - PORT=3030
    ports:
      - 3030:3030
    depends_on:
      - product-db
  sales-api:
    container_name: sales-api
    build: './sales-api'
    environment:
      - PORT=8083
    ports:
      - 8083:8083
    depends_on:
      - sales-db
